/*
 * ForgeRock AM OAuth2Client API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.am.agents.oauth2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * OAuth2ClientSignEncOAuth2ClientConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-09T15:43:26.593+01:00")
public class SignEncOAuth2ClientConfig {
  @JsonProperty("tokenEndpointAuthSigningAlgorithm")
  private StringValue tokenEndpointAuthSigningAlgorithm = null;

  @JsonProperty("jwkSet")
  private ObjectValue jwkSet = null;

  @JsonProperty("jwksCacheTimeout")
  private IntegerValue jwksCacheTimeout = null;

  @JsonProperty("idTokenEncryptionMethod")
  private StringValue idTokenEncryptionMethod = null;

  @JsonProperty("clientJwtPublicKey")
  private ObjectValue clientJwtPublicKey = null;

  @JsonProperty("idTokenSignedResponseAlg")
  private StringValue idTokenSignedResponseAlg = null;

  @JsonProperty("userinfoEncryptedResponseAlg")
  private ObjectValue userinfoEncryptedResponseAlg = null;

  @JsonProperty("userinfoSignedResponseAlg")
  private ObjectValue userinfoSignedResponseAlg = null;

  @JsonProperty("requestParameterEncryptedAlg")
  private ObjectValue requestParameterEncryptedAlg = null;

  @JsonProperty("requestParameterSignedAlg")
  private ObjectValue requestParameterSignedAlg = null;

  @JsonProperty("userinfoResponseFormat")
  private StringValue userinfoResponseFormat = null;

  @JsonProperty("idTokenEncryptionEnabled")
  private BooleanValue idTokenEncryptionEnabled = null;

  @JsonProperty("idTokenPublicEncryptionKey")
  private ObjectValue idTokenPublicEncryptionKey = null;

  @JsonProperty("jwksUri")
  private StringValue jwksUri = null;

  @JsonProperty("idTokenEncryptionAlgorithm")
  private StringValue idTokenEncryptionAlgorithm = null;

  @JsonProperty("requestParameterEncryptedEncryptionAlgorithm")
  private StringValue requestParameterEncryptedEncryptionAlgorithm = null;

  @JsonProperty("userinfoEncryptedResponseEncryptionAlgorithm")
  private StringValue userinfoEncryptedResponseEncryptionAlgorithm = null;

  @JsonProperty("jwkStoreCacheMissCacheTime")
  private IntegerValue jwkStoreCacheMissCacheTime = null;

  @JsonProperty("publicKeyLocation")
  private StringValue publicKeyLocation = null;

  public SignEncOAuth2ClientConfig tokenEndpointAuthSigningAlgorithm(StringValue tokenEndpointAuthSigningAlgorithm) {
    this.tokenEndpointAuthSigningAlgorithm = tokenEndpointAuthSigningAlgorithm;
    return this;
  }

   /**
   * Get tokenEndpointAuthSigningAlgorithm
   * @return tokenEndpointAuthSigningAlgorithm
  **/
  @ApiModelProperty(value = "")
  public StringValue getTokenEndpointAuthSigningAlgorithm() {
    return tokenEndpointAuthSigningAlgorithm;
  }

  public void setTokenEndpointAuthSigningAlgorithm(StringValue tokenEndpointAuthSigningAlgorithm) {
    this.tokenEndpointAuthSigningAlgorithm = tokenEndpointAuthSigningAlgorithm;
  }

  public SignEncOAuth2ClientConfig jwkSet(ObjectValue jwkSet) {
    this.jwkSet = jwkSet;
    return this;
  }

   /**
   * Get jwkSet
   * @return jwkSet
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getJwkSet() {
    return jwkSet;
  }

  public void setJwkSet(ObjectValue jwkSet) {
    this.jwkSet = jwkSet;
  }

  public SignEncOAuth2ClientConfig jwksCacheTimeout(IntegerValue jwksCacheTimeout) {
    this.jwksCacheTimeout = jwksCacheTimeout;
    return this;
  }

   /**
   * Get jwksCacheTimeout
   * @return jwksCacheTimeout
  **/
  @ApiModelProperty(value = "")
  public IntegerValue getJwksCacheTimeout() {
    return jwksCacheTimeout;
  }

  public void setJwksCacheTimeout(IntegerValue jwksCacheTimeout) {
    this.jwksCacheTimeout = jwksCacheTimeout;
  }

  public SignEncOAuth2ClientConfig idTokenEncryptionMethod(StringValue idTokenEncryptionMethod) {
    this.idTokenEncryptionMethod = idTokenEncryptionMethod;
    return this;
  }

   /**
   * Get idTokenEncryptionMethod
   * @return idTokenEncryptionMethod
  **/
  @ApiModelProperty(value = "")
  public StringValue getIdTokenEncryptionMethod() {
    return idTokenEncryptionMethod;
  }

  public void setIdTokenEncryptionMethod(StringValue idTokenEncryptionMethod) {
    this.idTokenEncryptionMethod = idTokenEncryptionMethod;
  }

  public SignEncOAuth2ClientConfig clientJwtPublicKey(ObjectValue clientJwtPublicKey) {
    this.clientJwtPublicKey = clientJwtPublicKey;
    return this;
  }

   /**
   * Get clientJwtPublicKey
   * @return clientJwtPublicKey
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getClientJwtPublicKey() {
    return clientJwtPublicKey;
  }

  public void setClientJwtPublicKey(ObjectValue clientJwtPublicKey) {
    this.clientJwtPublicKey = clientJwtPublicKey;
  }

  public SignEncOAuth2ClientConfig idTokenSignedResponseAlg(StringValue idTokenSignedResponseAlg) {
    this.idTokenSignedResponseAlg = idTokenSignedResponseAlg;
    return this;
  }

   /**
   * Get idTokenSignedResponseAlg
   * @return idTokenSignedResponseAlg
  **/
  @ApiModelProperty(value = "")
  public StringValue getIdTokenSignedResponseAlg() {
    return idTokenSignedResponseAlg;
  }

  public void setIdTokenSignedResponseAlg(StringValue idTokenSignedResponseAlg) {
    this.idTokenSignedResponseAlg = idTokenSignedResponseAlg;
  }

  public SignEncOAuth2ClientConfig userinfoEncryptedResponseAlg(ObjectValue userinfoEncryptedResponseAlg) {
    this.userinfoEncryptedResponseAlg = userinfoEncryptedResponseAlg;
    return this;
  }

   /**
   * Get userinfoEncryptedResponseAlg
   * @return userinfoEncryptedResponseAlg
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getUserinfoEncryptedResponseAlg() {
    return userinfoEncryptedResponseAlg;
  }

  public void setUserinfoEncryptedResponseAlg(ObjectValue userinfoEncryptedResponseAlg) {
    this.userinfoEncryptedResponseAlg = userinfoEncryptedResponseAlg;
  }

  public SignEncOAuth2ClientConfig userinfoSignedResponseAlg(ObjectValue userinfoSignedResponseAlg) {
    this.userinfoSignedResponseAlg = userinfoSignedResponseAlg;
    return this;
  }

   /**
   * Get userinfoSignedResponseAlg
   * @return userinfoSignedResponseAlg
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getUserinfoSignedResponseAlg() {
    return userinfoSignedResponseAlg;
  }

  public void setUserinfoSignedResponseAlg(ObjectValue userinfoSignedResponseAlg) {
    this.userinfoSignedResponseAlg = userinfoSignedResponseAlg;
  }

  public SignEncOAuth2ClientConfig requestParameterEncryptedAlg(ObjectValue requestParameterEncryptedAlg) {
    this.requestParameterEncryptedAlg = requestParameterEncryptedAlg;
    return this;
  }

   /**
   * Get requestParameterEncryptedAlg
   * @return requestParameterEncryptedAlg
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getRequestParameterEncryptedAlg() {
    return requestParameterEncryptedAlg;
  }

  public void setRequestParameterEncryptedAlg(ObjectValue requestParameterEncryptedAlg) {
    this.requestParameterEncryptedAlg = requestParameterEncryptedAlg;
  }

  public SignEncOAuth2ClientConfig requestParameterSignedAlg(ObjectValue requestParameterSignedAlg) {
    this.requestParameterSignedAlg = requestParameterSignedAlg;
    return this;
  }

   /**
   * Get requestParameterSignedAlg
   * @return requestParameterSignedAlg
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getRequestParameterSignedAlg() {
    return requestParameterSignedAlg;
  }

  public void setRequestParameterSignedAlg(ObjectValue requestParameterSignedAlg) {
    this.requestParameterSignedAlg = requestParameterSignedAlg;
  }

  public SignEncOAuth2ClientConfig userinfoResponseFormat(StringValue userinfoResponseFormat) {
    this.userinfoResponseFormat = userinfoResponseFormat;
    return this;
  }

   /**
   * Get userinfoResponseFormat
   * @return userinfoResponseFormat
  **/
  @ApiModelProperty(value = "")
  public StringValue getUserinfoResponseFormat() {
    return userinfoResponseFormat;
  }

  public void setUserinfoResponseFormat(StringValue userinfoResponseFormat) {
    this.userinfoResponseFormat = userinfoResponseFormat;
  }

  public SignEncOAuth2ClientConfig idTokenEncryptionEnabled(BooleanValue idTokenEncryptionEnabled) {
    this.idTokenEncryptionEnabled = idTokenEncryptionEnabled;
    return this;
  }

   /**
   * Get idTokenEncryptionEnabled
   * @return idTokenEncryptionEnabled
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getIdTokenEncryptionEnabled() {
    return idTokenEncryptionEnabled;
  }

  public void setIdTokenEncryptionEnabled(BooleanValue idTokenEncryptionEnabled) {
    this.idTokenEncryptionEnabled = idTokenEncryptionEnabled;
  }

  public SignEncOAuth2ClientConfig idTokenPublicEncryptionKey(ObjectValue idTokenPublicEncryptionKey) {
    this.idTokenPublicEncryptionKey = idTokenPublicEncryptionKey;
    return this;
  }

   /**
   * Get idTokenPublicEncryptionKey
   * @return idTokenPublicEncryptionKey
  **/
  @ApiModelProperty(value = "")
  public ObjectValue getIdTokenPublicEncryptionKey() {
    return idTokenPublicEncryptionKey;
  }

  public void setIdTokenPublicEncryptionKey(ObjectValue idTokenPublicEncryptionKey) {
    this.idTokenPublicEncryptionKey = idTokenPublicEncryptionKey;
  }

  public SignEncOAuth2ClientConfig jwksUri(StringValue jwksUri) {
    this.jwksUri = jwksUri;
    return this;
  }

   /**
   * Get jwksUri
   * @return jwksUri
  **/
  @ApiModelProperty(value = "")
  public StringValue getJwksUri() {
    return jwksUri;
  }

  public void setJwksUri(StringValue jwksUri) {
    this.jwksUri = jwksUri;
  }

  public SignEncOAuth2ClientConfig idTokenEncryptionAlgorithm(StringValue idTokenEncryptionAlgorithm) {
    this.idTokenEncryptionAlgorithm = idTokenEncryptionAlgorithm;
    return this;
  }

   /**
   * Get idTokenEncryptionAlgorithm
   * @return idTokenEncryptionAlgorithm
  **/
  @ApiModelProperty(value = "")
  public StringValue getIdTokenEncryptionAlgorithm() {
    return idTokenEncryptionAlgorithm;
  }

  public void setIdTokenEncryptionAlgorithm(StringValue idTokenEncryptionAlgorithm) {
    this.idTokenEncryptionAlgorithm = idTokenEncryptionAlgorithm;
  }

  public SignEncOAuth2ClientConfig requestParameterEncryptedEncryptionAlgorithm(StringValue requestParameterEncryptedEncryptionAlgorithm) {
    this.requestParameterEncryptedEncryptionAlgorithm = requestParameterEncryptedEncryptionAlgorithm;
    return this;
  }

   /**
   * Get requestParameterEncryptedEncryptionAlgorithm
   * @return requestParameterEncryptedEncryptionAlgorithm
  **/
  @ApiModelProperty(value = "")
  public StringValue getRequestParameterEncryptedEncryptionAlgorithm() {
    return requestParameterEncryptedEncryptionAlgorithm;
  }

  public void setRequestParameterEncryptedEncryptionAlgorithm(StringValue requestParameterEncryptedEncryptionAlgorithm) {
    this.requestParameterEncryptedEncryptionAlgorithm = requestParameterEncryptedEncryptionAlgorithm;
  }

  public SignEncOAuth2ClientConfig userinfoEncryptedResponseEncryptionAlgorithm(StringValue userinfoEncryptedResponseEncryptionAlgorithm) {
    this.userinfoEncryptedResponseEncryptionAlgorithm = userinfoEncryptedResponseEncryptionAlgorithm;
    return this;
  }

   /**
   * Get userinfoEncryptedResponseEncryptionAlgorithm
   * @return userinfoEncryptedResponseEncryptionAlgorithm
  **/
  @ApiModelProperty(value = "")
  public StringValue getUserinfoEncryptedResponseEncryptionAlgorithm() {
    return userinfoEncryptedResponseEncryptionAlgorithm;
  }

  public void setUserinfoEncryptedResponseEncryptionAlgorithm(StringValue userinfoEncryptedResponseEncryptionAlgorithm) {
    this.userinfoEncryptedResponseEncryptionAlgorithm = userinfoEncryptedResponseEncryptionAlgorithm;
  }

  public SignEncOAuth2ClientConfig jwkStoreCacheMissCacheTime(IntegerValue jwkStoreCacheMissCacheTime) {
    this.jwkStoreCacheMissCacheTime = jwkStoreCacheMissCacheTime;
    return this;
  }

   /**
   * Get jwkStoreCacheMissCacheTime
   * @return jwkStoreCacheMissCacheTime
  **/
  @ApiModelProperty(value = "")
  public IntegerValue getJwkStoreCacheMissCacheTime() {
    return jwkStoreCacheMissCacheTime;
  }

  public void setJwkStoreCacheMissCacheTime(IntegerValue jwkStoreCacheMissCacheTime) {
    this.jwkStoreCacheMissCacheTime = jwkStoreCacheMissCacheTime;
  }

  public SignEncOAuth2ClientConfig publicKeyLocation(StringValue publicKeyLocation) {
    this.publicKeyLocation = publicKeyLocation;
    return this;
  }

   /**
   * Get publicKeyLocation
   * @return publicKeyLocation
  **/
  @ApiModelProperty(value = "")
  public StringValue getPublicKeyLocation() {
    return publicKeyLocation;
  }

  public void setPublicKeyLocation(StringValue publicKeyLocation) {
    this.publicKeyLocation = publicKeyLocation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignEncOAuth2ClientConfig oauth2ClientSignEncOAuth2ClientConfig = (SignEncOAuth2ClientConfig) o;
    return Objects.equals(this.tokenEndpointAuthSigningAlgorithm, oauth2ClientSignEncOAuth2ClientConfig.tokenEndpointAuthSigningAlgorithm) &&
        Objects.equals(this.jwkSet, oauth2ClientSignEncOAuth2ClientConfig.jwkSet) &&
        Objects.equals(this.jwksCacheTimeout, oauth2ClientSignEncOAuth2ClientConfig.jwksCacheTimeout) &&
        Objects.equals(this.idTokenEncryptionMethod, oauth2ClientSignEncOAuth2ClientConfig.idTokenEncryptionMethod) &&
        Objects.equals(this.clientJwtPublicKey, oauth2ClientSignEncOAuth2ClientConfig.clientJwtPublicKey) &&
        Objects.equals(this.idTokenSignedResponseAlg, oauth2ClientSignEncOAuth2ClientConfig.idTokenSignedResponseAlg) &&
        Objects.equals(this.userinfoEncryptedResponseAlg, oauth2ClientSignEncOAuth2ClientConfig.userinfoEncryptedResponseAlg) &&
        Objects.equals(this.userinfoSignedResponseAlg, oauth2ClientSignEncOAuth2ClientConfig.userinfoSignedResponseAlg) &&
        Objects.equals(this.requestParameterEncryptedAlg, oauth2ClientSignEncOAuth2ClientConfig.requestParameterEncryptedAlg) &&
        Objects.equals(this.requestParameterSignedAlg, oauth2ClientSignEncOAuth2ClientConfig.requestParameterSignedAlg) &&
        Objects.equals(this.userinfoResponseFormat, oauth2ClientSignEncOAuth2ClientConfig.userinfoResponseFormat) &&
        Objects.equals(this.idTokenEncryptionEnabled, oauth2ClientSignEncOAuth2ClientConfig.idTokenEncryptionEnabled) &&
        Objects.equals(this.idTokenPublicEncryptionKey, oauth2ClientSignEncOAuth2ClientConfig.idTokenPublicEncryptionKey) &&
        Objects.equals(this.jwksUri, oauth2ClientSignEncOAuth2ClientConfig.jwksUri) &&
        Objects.equals(this.idTokenEncryptionAlgorithm, oauth2ClientSignEncOAuth2ClientConfig.idTokenEncryptionAlgorithm) &&
        Objects.equals(this.requestParameterEncryptedEncryptionAlgorithm, oauth2ClientSignEncOAuth2ClientConfig.requestParameterEncryptedEncryptionAlgorithm) &&
        Objects.equals(this.userinfoEncryptedResponseEncryptionAlgorithm, oauth2ClientSignEncOAuth2ClientConfig.userinfoEncryptedResponseEncryptionAlgorithm) &&
        Objects.equals(this.jwkStoreCacheMissCacheTime, oauth2ClientSignEncOAuth2ClientConfig.jwkStoreCacheMissCacheTime) &&
        Objects.equals(this.publicKeyLocation, oauth2ClientSignEncOAuth2ClientConfig.publicKeyLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenEndpointAuthSigningAlgorithm, jwkSet, jwksCacheTimeout, idTokenEncryptionMethod, clientJwtPublicKey, idTokenSignedResponseAlg, userinfoEncryptedResponseAlg, userinfoSignedResponseAlg, requestParameterEncryptedAlg, requestParameterSignedAlg, userinfoResponseFormat, idTokenEncryptionEnabled, idTokenPublicEncryptionKey, jwksUri, idTokenEncryptionAlgorithm, requestParameterEncryptedEncryptionAlgorithm, userinfoEncryptedResponseEncryptionAlgorithm, jwkStoreCacheMissCacheTime, publicKeyLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuth2ClientSignEncOAuth2ClientConfig {\n");

    sb.append("    tokenEndpointAuthSigningAlgorithm: ").append(toIndentedString(tokenEndpointAuthSigningAlgorithm)).append("\n");
    sb.append("    jwkSet: ").append(toIndentedString(jwkSet)).append("\n");
    sb.append("    jwksCacheTimeout: ").append(toIndentedString(jwksCacheTimeout)).append("\n");
    sb.append("    idTokenEncryptionMethod: ").append(toIndentedString(idTokenEncryptionMethod)).append("\n");
    sb.append("    clientJwtPublicKey: ").append(toIndentedString(clientJwtPublicKey)).append("\n");
    sb.append("    idTokenSignedResponseAlg: ").append(toIndentedString(idTokenSignedResponseAlg)).append("\n");
    sb.append("    userinfoEncryptedResponseAlg: ").append(toIndentedString(userinfoEncryptedResponseAlg)).append("\n");
    sb.append("    userinfoSignedResponseAlg: ").append(toIndentedString(userinfoSignedResponseAlg)).append("\n");
    sb.append("    requestParameterEncryptedAlg: ").append(toIndentedString(requestParameterEncryptedAlg)).append("\n");
    sb.append("    requestParameterSignedAlg: ").append(toIndentedString(requestParameterSignedAlg)).append("\n");
    sb.append("    userinfoResponseFormat: ").append(toIndentedString(userinfoResponseFormat)).append("\n");
    sb.append("    idTokenEncryptionEnabled: ").append(toIndentedString(idTokenEncryptionEnabled)).append("\n");
    sb.append("    idTokenPublicEncryptionKey: ").append(toIndentedString(idTokenPublicEncryptionKey)).append("\n");
    sb.append("    jwksUri: ").append(toIndentedString(jwksUri)).append("\n");
    sb.append("    idTokenEncryptionAlgorithm: ").append(toIndentedString(idTokenEncryptionAlgorithm)).append("\n");
    sb.append("    requestParameterEncryptedEncryptionAlgorithm: ").append(toIndentedString(requestParameterEncryptedEncryptionAlgorithm)).append("\n");
    sb.append("    userinfoEncryptedResponseEncryptionAlgorithm: ").append(toIndentedString(userinfoEncryptedResponseEncryptionAlgorithm)).append("\n");
    sb.append("    jwkStoreCacheMissCacheTime: ").append(toIndentedString(jwkStoreCacheMissCacheTime)).append("\n");
    sb.append("    publicKeyLocation: ").append(toIndentedString(publicKeyLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

