/*
 * ForgeRock IDM Users API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Terms Accepted
 */
@ApiModel(description = "Terms Accepted")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-21T15:18:23.299Z")
public class TermsAccepted {
  @JsonProperty("termsVersion")
  private String termsVersion = null;

  @JsonProperty("iso8601date")
  private String iso8601date = null;

  public TermsAccepted termsVersion(String termsVersion) {
    this.termsVersion = termsVersion;
    return this;
  }

   /**
   * Terms &amp; Conditions Version
   * @return termsVersion
  **/
  @ApiModelProperty(value = "Terms & Conditions Version")
  public String getTermsVersion() {
    return termsVersion;
  }

  public void setTermsVersion(String termsVersion) {
    this.termsVersion = termsVersion;
  }

  public TermsAccepted iso8601date(String iso8601date) {
    this.iso8601date = iso8601date;
    return this;
  }

   /**
   * ISO 8601 Date and time format
   * @return iso8601date
  **/
  @ApiModelProperty(value = "ISO 8601 Date and time format")
  public String getIso8601date() {
    return iso8601date;
  }

  public void setIso8601date(String iso8601date) {
    this.iso8601date = iso8601date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TermsAccepted termsAccepted = (TermsAccepted) o;
    return Objects.equals(this.termsVersion, termsAccepted.termsVersion) &&
        Objects.equals(this.iso8601date, termsAccepted.iso8601date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(termsVersion, iso8601date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TermsAccepted {\n");
    
    sb.append("    termsVersion: ").append(toIndentedString(termsVersion)).append("\n");
    sb.append("    iso8601date: ").append(toIndentedString(iso8601date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

