/*
 * ForgeRock IDM Users API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.EffectiveAssignment;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.EffectiveRole;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.KBAInfoItems;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.LastChanged;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.LastSyncTimestamp;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.Manager;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.Preferences;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.TermsAccepted;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.UserAuthzRoles;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.UserReports;
import uk.gov.hmcts.reform.idam.api.fr.idm.manage.user.model.UserRoles;

/**
 * User
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:48:59.475Z")
public class User {
  @JsonProperty("_id")
  private String id = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("kbaInfo")
  private List<KBAInfoItems> kbaInfo = null;

  @JsonProperty("preferences")
  private Preferences preferences = null;

  @JsonProperty("mail")
  private String mail = null;

  @JsonProperty("sn")
  private String sn = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("address2")
  private String address2 = null;

  @JsonProperty("givenName")
  private String givenName = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("postalCode")
  private String postalCode = null;

  @JsonProperty("accountStatus")
  private String accountStatus = null;

  @JsonProperty("roles")
  private List<UserRoles> roles = null;

  @JsonProperty("authzRoles")
  private List<UserAuthzRoles> authzRoles = null;

  @JsonProperty("reports")
  private List<UserReports> reports = null;

  @JsonProperty("effectiveRoles")
  private List<EffectiveRole> effectiveRoles = null;

  @JsonProperty("effectiveAssignments")
  private List<EffectiveAssignment> effectiveAssignments = null;

  @JsonProperty("telephoneNumber")
  private String telephoneNumber = null;

  @JsonProperty("stateProvince")
  private String stateProvince = null;

  @JsonProperty("postalAddress")
  private String postalAddress = null;

  @JsonProperty("userName")
  private String userName = null;

  @JsonProperty("manager")
  private Manager manager = null;

  @JsonProperty("lastSync")
  private LastSyncTimestamp lastSync = null;

  @JsonProperty("termsAccepted")
  private TermsAccepted termsAccepted = null;

  @JsonProperty("lastChanged")
  private LastChanged lastChanged = null;

  @JsonProperty("consentedMappings")
  private List<List<Object>> consentedMappings = null;

  public User id(String id) {
    this.id = id;
    return this;
  }

   /**
   * User ID
   * @return id
  **/
  @ApiModelProperty(value = "User ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public User password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password
   * @return password
  **/
  @ApiModelProperty(value = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public User kbaInfo(List<KBAInfoItems> kbaInfo) {
    this.kbaInfo = kbaInfo;
    return this;
  }

  public User addKbaInfoItem(KBAInfoItems kbaInfoItem) {
    if (this.kbaInfo == null) {
      this.kbaInfo = new ArrayList<>();
    }
    this.kbaInfo.add(kbaInfoItem);
    return this;
  }

   /**
   * KBA Info
   * @return kbaInfo
  **/
  @ApiModelProperty(value = "KBA Info")
  public List<KBAInfoItems> getKbaInfo() {
    return kbaInfo;
  }

  public void setKbaInfo(List<KBAInfoItems> kbaInfo) {
    this.kbaInfo = kbaInfo;
  }

  public User preferences(Preferences preferences) {
    this.preferences = preferences;
    return this;
  }

   /**
   * Get preferences
   * @return preferences
  **/
  @ApiModelProperty(value = "")
  public Preferences getPreferences() {
    return preferences;
  }

  public void setPreferences(Preferences preferences) {
    this.preferences = preferences;
  }

  public User mail(String mail) {
    this.mail = mail;
    return this;
  }

   /**
   * Email Address
   * @return mail
  **/
  @ApiModelProperty(required = true, value = "Email Address")
  public String getMail() {
    return mail;
  }

  public void setMail(String mail) {
    this.mail = mail;
  }

  public User sn(String sn) {
    this.sn = sn;
    return this;
  }

   /**
   * Last Name
   * @return sn
  **/
  @ApiModelProperty(required = true, value = "Last Name")
  public String getSn() {
    return sn;
  }

  public void setSn(String sn) {
    this.sn = sn;
  }

  public User description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public User address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Address 2
   * @return address2
  **/
  @ApiModelProperty(value = "Address 2")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public User givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * First Name
   * @return givenName
  **/
  @ApiModelProperty(required = true, value = "First Name")
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public User city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City
   * @return city
  **/
  @ApiModelProperty(value = "City")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public User country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country
   * @return country
  **/
  @ApiModelProperty(value = "Country")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public User postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal Code
   * @return postalCode
  **/
  @ApiModelProperty(value = "Postal Code")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public User accountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * Status
   * @return accountStatus
  **/
  @ApiModelProperty(value = "Status")
  public String getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
  }

  public User roles(List<UserRoles> roles) {
    this.roles = roles;
    return this;
  }

  public User addRolesItem(UserRoles rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Provisioning Roles
   * @return roles
  **/
  @ApiModelProperty(value = "Provisioning Roles")
  public List<UserRoles> getRoles() {
    return roles;
  }

  public void setRoles(List<UserRoles> roles) {
    this.roles = roles;
  }

  public User authzRoles(List<UserAuthzRoles> authzRoles) {
    this.authzRoles = authzRoles;
    return this;
  }

  public User addAuthzRolesItem(UserAuthzRoles authzRolesItem) {
    if (this.authzRoles == null) {
      this.authzRoles = new ArrayList<>();
    }
    this.authzRoles.add(authzRolesItem);
    return this;
  }

   /**
   * Authorization Roles
   * @return authzRoles
  **/
  @ApiModelProperty(value = "Authorization Roles")
  public List<UserAuthzRoles> getAuthzRoles() {
    return authzRoles;
  }

  public void setAuthzRoles(List<UserAuthzRoles> authzRoles) {
    this.authzRoles = authzRoles;
  }

  public User reports(List<UserReports> reports) {
    this.reports = reports;
    return this;
  }

  public User addReportsItem(UserReports reportsItem) {
    if (this.reports == null) {
      this.reports = new ArrayList<>();
    }
    this.reports.add(reportsItem);
    return this;
  }

   /**
   * Direct Reports
   * @return reports
  **/
  @ApiModelProperty(value = "Direct Reports")
  public List<UserReports> getReports() {
    return reports;
  }

  public void setReports(List<UserReports> reports) {
    this.reports = reports;
  }

  public User effectiveRoles(List<EffectiveRole> effectiveRoles) {
    this.effectiveRoles = effectiveRoles;
    return this;
  }

  public User addEffectiveRolesItem(EffectiveRole effectiveRolesItem) {
    if (this.effectiveRoles == null) {
      this.effectiveRoles = new ArrayList<>();
    }
    this.effectiveRoles.add(effectiveRolesItem);
    return this;
  }

   /**
   * Effective Roles
   * @return effectiveRoles
  **/
  @ApiModelProperty(value = "Effective Roles")
  public List<EffectiveRole> getEffectiveRoles() {
    return effectiveRoles;
  }

  public void setEffectiveRoles(List<EffectiveRole> effectiveRoles) {
    this.effectiveRoles = effectiveRoles;
  }

  public User effectiveAssignments(List<EffectiveAssignment> effectiveAssignments) {
    this.effectiveAssignments = effectiveAssignments;
    return this;
  }

  public User addEffectiveAssignmentsItem(EffectiveAssignment effectiveAssignmentsItem) {
    if (this.effectiveAssignments == null) {
      this.effectiveAssignments = new ArrayList<>();
    }
    this.effectiveAssignments.add(effectiveAssignmentsItem);
    return this;
  }

   /**
   * Effective Assignments
   * @return effectiveAssignments
  **/
  @ApiModelProperty(value = "Effective Assignments")
  public List<EffectiveAssignment> getEffectiveAssignments() {
    return effectiveAssignments;
  }

  public void setEffectiveAssignments(List<EffectiveAssignment> effectiveAssignments) {
    this.effectiveAssignments = effectiveAssignments;
  }

  public User telephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
    return this;
  }

   /**
   * Mobile Phone
   * @return telephoneNumber
  **/
  @ApiModelProperty(value = "Mobile Phone")
  public String getTelephoneNumber() {
    return telephoneNumber;
  }

  public void setTelephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }

  public User stateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * State/Province
   * @return stateProvince
  **/
  @ApiModelProperty(value = "State/Province")
  public String getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }

  public User postalAddress(String postalAddress) {
    this.postalAddress = postalAddress;
    return this;
  }

   /**
   * Address 1
   * @return postalAddress
  **/
  @ApiModelProperty(value = "Address 1")
  public String getPostalAddress() {
    return postalAddress;
  }

  public void setPostalAddress(String postalAddress) {
    this.postalAddress = postalAddress;
  }

  public User userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Username
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Username")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public User manager(Manager manager) {
    this.manager = manager;
    return this;
  }

   /**
   * Get manager
   * @return manager
  **/
  @ApiModelProperty(value = "")
  public Manager getManager() {
    return manager;
  }

  public void setManager(Manager manager) {
    this.manager = manager;
  }

  public User lastSync(LastSyncTimestamp lastSync) {
    this.lastSync = lastSync;
    return this;
  }

   /**
   * Get lastSync
   * @return lastSync
  **/
  @ApiModelProperty(value = "")
  public LastSyncTimestamp getLastSync() {
    return lastSync;
  }

  public void setLastSync(LastSyncTimestamp lastSync) {
    this.lastSync = lastSync;
  }

  public User termsAccepted(TermsAccepted termsAccepted) {
    this.termsAccepted = termsAccepted;
    return this;
  }

   /**
   * Get termsAccepted
   * @return termsAccepted
  **/
  @ApiModelProperty(value = "")
  public TermsAccepted getTermsAccepted() {
    return termsAccepted;
  }

  public void setTermsAccepted(TermsAccepted termsAccepted) {
    this.termsAccepted = termsAccepted;
  }

  public User lastChanged(LastChanged lastChanged) {
    this.lastChanged = lastChanged;
    return this;
  }

   /**
   * Get lastChanged
   * @return lastChanged
  **/
  @ApiModelProperty(value = "")
  public LastChanged getLastChanged() {
    return lastChanged;
  }

  public void setLastChanged(LastChanged lastChanged) {
    this.lastChanged = lastChanged;
  }

  public User consentedMappings(List<List<Object>> consentedMappings) {
    this.consentedMappings = consentedMappings;
    return this;
  }

  public User addConsentedMappingsItem(List<Object> consentedMappingsItem) {
    if (this.consentedMappings == null) {
      this.consentedMappings = new ArrayList<>();
    }
    this.consentedMappings.add(consentedMappingsItem);
    return this;
  }

   /**
   * Consented Mappings
   * @return consentedMappings
  **/
  @ApiModelProperty(value = "Consented Mappings")
  public List<List<Object>> getConsentedMappings() {
    return consentedMappings;
  }

  public void setConsentedMappings(List<List<Object>> consentedMappings) {
    this.consentedMappings = consentedMappings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.password, user.password) &&
        Objects.equals(this.kbaInfo, user.kbaInfo) &&
        Objects.equals(this.preferences, user.preferences) &&
        Objects.equals(this.mail, user.mail) &&
        Objects.equals(this.sn, user.sn) &&
        Objects.equals(this.description, user.description) &&
        Objects.equals(this.address2, user.address2) &&
        Objects.equals(this.givenName, user.givenName) &&
        Objects.equals(this.city, user.city) &&
        Objects.equals(this.country, user.country) &&
        Objects.equals(this.postalCode, user.postalCode) &&
        Objects.equals(this.accountStatus, user.accountStatus) &&
        Objects.equals(this.roles, user.roles) &&
        Objects.equals(this.authzRoles, user.authzRoles) &&
        Objects.equals(this.reports, user.reports) &&
        Objects.equals(this.effectiveRoles, user.effectiveRoles) &&
        Objects.equals(this.effectiveAssignments, user.effectiveAssignments) &&
        Objects.equals(this.telephoneNumber, user.telephoneNumber) &&
        Objects.equals(this.stateProvince, user.stateProvince) &&
        Objects.equals(this.postalAddress, user.postalAddress) &&
        Objects.equals(this.userName, user.userName) &&
        Objects.equals(this.manager, user.manager) &&
        Objects.equals(this.lastSync, user.lastSync) &&
        Objects.equals(this.termsAccepted, user.termsAccepted) &&
        Objects.equals(this.lastChanged, user.lastChanged) &&
        Objects.equals(this.consentedMappings, user.consentedMappings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, password, kbaInfo, preferences, mail, sn, description, address2, givenName, city, country, postalCode, accountStatus, roles, authzRoles, reports, effectiveRoles, effectiveAssignments, telephoneNumber, stateProvince, postalAddress, userName, manager, lastSync, termsAccepted, lastChanged, consentedMappings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    kbaInfo: ").append(toIndentedString(kbaInfo)).append("\n");
    sb.append("    preferences: ").append(toIndentedString(preferences)).append("\n");
    sb.append("    mail: ").append(toIndentedString(mail)).append("\n");
    sb.append("    sn: ").append(toIndentedString(sn)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    authzRoles: ").append(toIndentedString(authzRoles)).append("\n");
    sb.append("    reports: ").append(toIndentedString(reports)).append("\n");
    sb.append("    effectiveRoles: ").append(toIndentedString(effectiveRoles)).append("\n");
    sb.append("    effectiveAssignments: ").append(toIndentedString(effectiveAssignments)).append("\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    postalAddress: ").append(toIndentedString(postalAddress)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("    lastSync: ").append(toIndentedString(lastSync)).append("\n");
    sb.append("    termsAccepted: ").append(toIndentedString(termsAccepted)).append("\n");
    sb.append("    lastChanged: ").append(toIndentedString(lastChanged)).append("\n");
    sb.append("    consentedMappings: ").append(toIndentedString(consentedMappings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

