/*
 * ForgeRock AM Agents API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.am.agents.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The type of a configuration entity is described as its ID, its name and whether or not it is a collection
 */
@ApiModel(description = "The type of a configuration entity is described as its ID, its name and whether or not it is a collection")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:48:57.857Z")
public class RestsmsType {
  @JsonProperty("_id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("collection")
  private Boolean collection = null;

  public RestsmsType id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier of the type
   * @return id
  **/
  @ApiModelProperty(value = "The identifier of the type")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RestsmsType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the type
   * @return name
  **/
  @ApiModelProperty(value = "The name of the type")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RestsmsType collection(Boolean collection) {
    this.collection = collection;
    return this;
  }

   /**
   * Whether the type is a collection or singleton configuration type
   * @return collection
  **/
  @ApiModelProperty(value = "Whether the type is a collection or singleton configuration type")
  public Boolean isCollection() {
    return collection;
  }

  public void setCollection(Boolean collection) {
    this.collection = collection;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestsmsType restsmsType = (RestsmsType) o;
    return Objects.equals(this.id, restsmsType.id) &&
        Objects.equals(this.name, restsmsType.name) &&
        Objects.equals(this.collection, restsmsType.collection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, collection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestsmsType {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    collection: ").append(toIndentedString(collection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

