/*
 * ForgeRock AM Agents API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.am.agents.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * JWE enc algorithm for encrypting UserInfo Responses. If userinfo encrypted response algorithm is specified, the default for this value is A128CBC-HS256. When user info encrypted response encryption is included, user info encrypted response algorithm MUST also be provided.&lt;br&gt;&lt;br&gt;OpenAM supports the following token encryption algorithms:&lt;ul&gt;&lt;li&gt;&lt;code&gt;A128GCM&lt;/code&gt;, &lt;code&gt;A192GCM&lt;/code&gt;, and &lt;code&gt;A256GCM&lt;/code&gt; - AES in Galois Counter Mode (GCM) authenticated encryption mode.&lt;/li&gt;&lt;li&gt;&lt;code&gt;A128CBC-HS256&lt;/code&gt;, &lt;code&gt;A192CBC-HS384&lt;/code&gt;, and &lt;code&gt;A256CBC-HS512&lt;/code&gt; - AES encryption in CBC mode, with HMAC-SHA-2 for integrity.&lt;/li&gt;&lt;/ul&gt;
 */
@ApiModel(description = "JWE enc algorithm for encrypting UserInfo Responses. If userinfo encrypted response algorithm is specified, the default for this value is A128CBC-HS256. When user info encrypted response encryption is included, user info encrypted response algorithm MUST also be provided.<br><br>OpenAM supports the following token encryption algorithms:<ul><li><code>A128GCM</code>, <code>A192GCM</code>, and <code>A256GCM</code> - AES in Galois Counter Mode (GCM) authenticated encryption mode.</li><li><code>A128CBC-HS256</code>, <code>A192CBC-HS384</code>, and <code>A256CBC-HS512</code> - AES encryption in CBC mode, with HMAC-SHA-2 for integrity.</li></ul>")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:48:57.857Z")
public class UserInfoEncryptedResponseEncryptionAlgorithm {
  @JsonProperty("inherited")
  private Boolean inherited = null;

  @JsonProperty("value")
  private String value = null;

  public UserInfoEncryptedResponseEncryptionAlgorithm inherited(Boolean inherited) {
    this.inherited = inherited;
    return this;
  }

   /**
   * Get inherited
   * @return inherited
  **/
  @ApiModelProperty(value = "")
  public Boolean isInherited() {
    return inherited;
  }

  public void setInherited(Boolean inherited) {
    this.inherited = inherited;
  }

  public UserInfoEncryptedResponseEncryptionAlgorithm value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfoEncryptedResponseEncryptionAlgorithm userInfoEncryptedResponseEncryptionAlgorithm = (UserInfoEncryptedResponseEncryptionAlgorithm) o;
    return Objects.equals(this.inherited, userInfoEncryptedResponseEncryptionAlgorithm.inherited) &&
        Objects.equals(this.value, userInfoEncryptedResponseEncryptionAlgorithm.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inherited, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfoEncryptedResponseEncryptionAlgorithm {\n");
    
    sb.append("    inherited: ").append(toIndentedString(inherited)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

