/*
 * ForgeRock IDM SelfService Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.selfservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Initialize the user self service stage. A set of requirements will be returned that will need to be fulfilled and sent to the submitRequirements action.
 */
@ApiModel(description = "Initialize the user self service stage. A set of requirements will be returned that will need to be fulfilled and sent to the submitRequirements action.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-21T15:18:23.943Z")
public class GetInitialRequirementsResponse {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("requirements")
  private Object requirements = null;

  public GetInitialRequirementsResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the self service interaction.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the self service interaction.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GetInitialRequirementsResponse tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * The stage description tag.
   * @return tag
  **/
  @ApiModelProperty(required = true, value = "The stage description tag.")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public GetInitialRequirementsResponse requirements(Object requirements) {
    this.requirements = requirements;
    return this;
  }

   /**
   * A JSON Schema object that defines the input that must be submitted to the submitRequirements action.
   * @return requirements
  **/
  @ApiModelProperty(required = true, value = "A JSON Schema object that defines the input that must be submitted to the submitRequirements action.")
  public Object getRequirements() {
    return requirements;
  }

  public void setRequirements(Object requirements) {
    this.requirements = requirements;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInitialRequirementsResponse getInitialRequirementsResponse = (GetInitialRequirementsResponse) o;
    return Objects.equals(this.type, getInitialRequirementsResponse.type) &&
        Objects.equals(this.tag, getInitialRequirementsResponse.tag) &&
        Objects.equals(this.requirements, getInitialRequirementsResponse.requirements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, tag, requirements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInitialRequirementsResponse {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

