/*
 * ForgeRock IDM SelfService Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.selfservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PolicyRequirements
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-21T15:18:23.943Z")
public class PolicyRequirements {
  @JsonProperty("policyRequirement")
  private String policyRequirement = null;

  public PolicyRequirements policyRequirement(String policyRequirement) {
    this.policyRequirement = policyRequirement;
    return this;
  }

   /**
   * Get policyRequirement
   * @return policyRequirement
  **/
  @ApiModelProperty(value = "")
  public String getPolicyRequirement() {
    return policyRequirement;
  }

  public void setPolicyRequirement(String policyRequirement) {
    this.policyRequirement = policyRequirement;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyRequirements policyRequirements = (PolicyRequirements) o;
    return Objects.equals(this.policyRequirement, policyRequirements.policyRequirement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyRequirement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyRequirements {\n");
    
    sb.append("    policyRequirement: ").append(toIndentedString(policyRequirement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

