/*
 * ForgeRock IDM SelfService Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.selfservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * If more requirements need fulfilling before the user registration process is completed, this response structure will be returned.
 */
@ApiModel(description = "If more requirements need fulfilling before the user registration process is completed, this response structure will be returned.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-13T13:49:38.439+01:00")
public class SubmitRequirementsResetResponse {
  @JsonProperty("token")
  private String token = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("requirements")
  private Object requirements = null;

  @JsonProperty("status")
  private SuccessObject status = null;

  public SubmitRequirementsResetResponse token(String token) {
    this.token = token;
    return this;
  }

   /**
   * A token for the process that must be returned with the next set of requirements when they have been fulfilled.
   * @return token
  **/
  @ApiModelProperty(required = true, value = "A token for the process that must be returned with the next set of requirements when they have been fulfilled.")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public SubmitRequirementsResetResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the self service interaction.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the self service interaction.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SubmitRequirementsResetResponse tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * The stage description tag.
   * @return tag
  **/
  @ApiModelProperty(required = true, value = "The stage description tag.")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public SubmitRequirementsResetResponse requirements(Object requirements) {
    this.requirements = requirements;
    return this;
  }

   /**
   * A JSON Schema object that defines the input that must be submitted to the submitRequirements action.
   * @return requirements
  **/
  @ApiModelProperty(required = true, value = "A JSON Schema object that defines the input that must be submitted to the submitRequirements action.")
  public Object getRequirements() {
    return requirements;
  }

  public void setRequirements(Object requirements) {
    this.requirements = requirements;
  }

  public SubmitRequirementsResetResponse status(SuccessObject status) {
    this.status = status;
    return this;
  }

   /**
   * If all the requirements have been fulfilled and the user registration process is complete, this response structure will be used.
   * @return status
  **/
  @ApiModelProperty(value = "If all the requirements have been fulfilled and the user registration process is complete, this response structure will be used.")
  public SuccessObject getStatus() {
    return status;
  }

  public void setStatus(SuccessObject status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitRequirementsResetResponse submitRequirementsResetResponse = (SubmitRequirementsResetResponse) o;
    return Objects.equals(this.token, submitRequirementsResetResponse.token) &&
        Objects.equals(this.type, submitRequirementsResetResponse.type) &&
        Objects.equals(this.tag, submitRequirementsResetResponse.tag) &&
        Objects.equals(this.requirements, submitRequirementsResetResponse.requirements) &&
        Objects.equals(this.status, submitRequirementsResetResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, type, tag, requirements, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitRequirementsResetResponse {\n");

    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

