swagger: '2.0'
info:
  version: '1.0'
  title: OpenAM
host: 'localhost:8080'
basePath: /openam/json
schemes:
  - http
consumes:
  - application/json
  - text/plain
  - multipart/form-data
produces:
  - application/json
paths:
  /json/policies:
    post:
      summary: 'Policies: Action: evaluate'
      operationId: evaluate
      description: Request policy decisions for specific resources
      tags:
        - Policies v2.1
      x-resourceVersion: '2.1'
      parameters:
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/_prettyPrint'
        - $ref: '#/parameters/realm'
        - $ref: '#/parameters/authorization'
        - in: body
          name: requestPayload
          required: true
          schema:
            $ref: '#/definitions/EvaluateRequest'
        - name: _action
          in: query
          required: true
          type: string
          enum:
            - evaluate
        - name: Accept-API-Version
          in: header
          required: true
          type: string
          enum:
            - resource=2.1
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/EvaluateResponse'
        '405':
          schema:
            $ref: '#/definitions/ApiError'
          description: The requested action is not supported on policies
        '500':
          schema:
            $ref: '#/definitions/ApiError'
          description: Unexpected server error happened during the process
        '501':
          schema:
            $ref: '#/definitions/ApiError'
          description: Unsupported operation
    put:
      summary: Create with Client-Assigned ID
      operationId: create
      description: Create or update policy
      tags:
        - Policies v2.1
      x-resourceVersion: '2.1'
      parameters:
        - name: resourceId
          in: path
          description: The unique identifier of the policy
          required: true
          type: string
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/_prettyPrint'
        - in: body
          name: requestPayload
          required: true
          schema:
            $ref: '#/definitions/PutPolicyRequest'
        - name: Accept-API-Version
          in: header
          required: true
          type: string
          enum:
            - resource=2.1
      responses:
        201:
          description: Success
          schema:
            $ref: '#/definitions/PutPolicyResponse'
          headers:
            Location:
              type: string
              description: Resource location in response to successful create operation.
        400:
          schema:
            $ref: '#/definitions/ApiError'
          description: |-
            Bad request error. The cause can be the following:
            * Missing privilege name
            * Invalid json provided in the request
            * Invalid value found in json
            * Invalid policy name provided in json
            * Resource name and JSON body name do not match
            * Query id missing UID
            * Invalid query id
            * Invalid search filter
            * Empty privilege name
            * Entitlement value was NULL
            * No resource type was expected
            * Policy defines invalid resource type
            * The provided resourceId does not match to the UUID in the json file
        403:
          schema:
            $ref: '#/definitions/ApiError'
          description: Permission Denied to access or create policy
definitions:
  EvaluateRequest:
    title: Evaluate Request
    description: Evaluate Request
    type: object
    required:
      - application
      - resources
    properties:
      resources:
        type: array
        items:
          type: string
        title: Resources
        description: Specifies the list of resources for which to return decisions
      application:
        type: string
        title: Application
        description: 'Holds the name of the application, and defaults to "iPlanetAMWebAgentService" if not specified'
      subject:
        type: object
        properties:
          ssoToken:
            type: string
            title: SSOToken
            description: The value is the SSO token ID string for the subject
          jwt:
            type: string
            title: JWT
            description: The value is a JWT string
          claims:
            type: object
            title: Claims
            description: The value is an object (map) of JWT claims to their values.
        title: Subject
        description: 'Holds an object that represents the subject. You can specify one or more of the following keys. If you specify multiple keys, the subject can have multiple associated principals, and you can use subject conditions corresponding to any type in the request'
      environment:
        type: object
        title: Environment
        description: Holds a map of keys to lists of values
  EvaluateResponse:
    type: array
    title: Evaluate and evaluateTree schema response
    description: Evaluate and evaluateTree schema response
    items:
      type: object
      properties:
        resource:
          type: string
          title: Resource
          description: Specifies the root resource for the decisions to return
        actions:
          type: object
          title: Actions
          description: A map of action name keys to Boolean values that indicate whether the action is allowed (true) or denied (false) for the specified resource
        attributes:
          type: object
          title: Attributes
          description: 'A map of attribute names to their values, if any response attributes are returned according to applicable policies'
        advices:
          type: object
          title: Advices
          description: 'A map of advice names to their values, if any advice is returned according to applicable policies'
  PutPolicyRequest:
    title: Policy Resource Schema
    description: Json schema for the policy resource
    type: object
    properties:
      name:
        type: string
        title: Name
        description: String matching the name of the application
      active:
        type: boolean
        title: Active flag
        description: 'Boolean indicating whether OpenAM considers the policy active for evaluation purposes, defaults to false'
      description:
        type: string
        title: Description
        description: String describing the policy
      applicationName:
        type: string
        title: Application name
        description: 'String containing the application name, such as "iPlanetAMWebAgentService", or "mypolicyset"'
      actionValues:
        type: object
        title: Action values
        description: 'Set of string action names, each set to a boolean indicating whether the action is allowed. Chosen from the available actions provided by the associated Managing Resource Types resource type'
      resources:
        type: array
        items:
          type: string
        title: Resources
        description: List of the resource name pattern strings to which the policy applies. Must conform to the pattern templates provided by the associated Managing Resource Types resource type
      subject:
        type: object
        title: Subject
        description: 'Specifies the subject conditions to which the policy applies, where subjects can be combined by using the built-in types "AND", "OR", and "NOT", and where subject implementations are pluggable'
      condition:
        type: object
        properties:
          type:
            type: string
          conditions:
            type: array
            items:
              type: object
            title: Condition
            description: 'Specifies environment conditions, where conditions can be combined by using the built-in types "AND", "OR", and "NOT", and where condition implementations are pluggable'
        title: Condition
        description: 'Specifies environment conditions, where conditions can be combined by using the built-in types "AND", "OR", and "NOT", and where condition implementations are pluggable'
      resourceTypeUuid:
        type: string
        title: Resource Type UUID
        description: The UUIDs of the resource type associated with the policy
      resourceAttributes:
        type: array
        items:
          type: object
        title: Resource Attributes
        description: List of attributes to return with decisions. These attributes are known as response attributes
      lastModifiedBy:
        type: string
        title: Last Modified By
        description: A string containing the universal identifier DN of the subject that most recently updated the policy
      lastModifiedDate:
        type: string
        title: Last Modified date
        description: 'An integer containing the last modified date and time, in number of seconds'
      createdBy:
        type: string
        title: Created By
        description: A string containing the universal identifier DN of the subject that created the policy
      creationDate:
        type: string
        title: Creation Date
        description: 'An integer containing the creation date and time, in number of seconds'
  PutPolicyResponse:
    title: Policy Resource Schema
    description: Json schema for the policy resource
    type: object
    properties:
      name:
        type: string
        title: Name
        description: String matching the name of the application
      active:
        type: boolean
        title: Active flag
        description: 'Boolean indicating whether OpenAM considers the policy active for evaluation purposes, defaults to false'
      description:
        type: string
        title: Description
        description: String describing the policy
      applicationName:
        type: string
        title: Application name
        description: 'String containing the application name, such as "iPlanetAMWebAgentService", or "mypolicyset"'
      actionValues:
        type: object
        title: Action values
        description: 'Set of string action names, each set to a boolean indicating whether the action is allowed. Chosen from the available actions provided by the associated Managing Resource Types resource type'
      resources:
        type: array
        items:
          type: string
        title: Resources
        description: List of the resource name pattern strings to which the policy applies. Must conform to the pattern templates provided by the associated Managing Resource Types resource type
      subject:
        type: object
        title: Subject
        description: 'Specifies the subject conditions to which the policy applies, where subjects can be combined by using the built-in types "AND", "OR", and "NOT", and where subject implementations are pluggable'
      condition:
        type: object
        properties:
          type:
            type: string
          conditions:
            type: array
            items:
              type: object
            title: Condition
            description: 'Specifies environment conditions, where conditions can be combined by using the built-in types "AND", "OR", and "NOT", and where condition implementations are pluggable'
        title: Condition
        description: 'Specifies environment conditions, where conditions can be combined by using the built-in types "AND", "OR", and "NOT", and where condition implementations are pluggable'
      resourceTypeUuid:
        type: string
        title: Resource Type UUID
        description: The UUIDs of the resource type associated with the policy
      resourceAttributes:
        type: array
        items:
          type: object
        title: Resource Attributes
        description: List of attributes to return with decisions. These attributes are known as response attributes
      lastModifiedBy:
        type: string
        title: Last Modified By
        description: A string containing the universal identifier DN of the subject that most recently updated the policy
      lastModifiedDate:
        type: string
        title: Last Modified date
        description: 'An integer containing the last modified date and time, in number of seconds'
      createdBy:
        type: string
        title: Created By
        description: A string containing the universal identifier DN of the subject that created the policy
      creationDate:
        type: string
        title: Creation Date
        description: 'An integer containing the creation date and time, in number of seconds'
parameters:
  _prettyPrint:
    name: _prettyPrint
    in: query
    description: Optional parameter requesting that the returned JSON resource content should be formatted to be more human readable.
    required: false
    type: boolean
  _fields:
    name: _fields
    in: query
    description: Optional parameter containing a comma separated list of field references specifying which fields of the targeted JSON resource should be returned.
    required: false
    type: string
    collectionFormat: csv
  realm:
    name: realm
    in: query
    description: Optional parameter specifying the realm.
    required: false
    type: string
  authorization:
    name: Cookie
    in: header
    required: false
    type: string
