swagger: '2.0'
info:
  version: 5.5.0
  title: Forgerock Shared Definitions
basePath: /forgerock/shared/definitions
tags:
  - name: Assignment
definitions:
  'PatchArray':
    type: array
    items:
      type: object
      properties:
        operation:
          type: string
          description: Operation to perform on the field
        field:
          type: string
          description: Target JSON Pointer of field to patch
        from:
          type: string
          description: Source JSON Pointer used with copy and move operations
        value:
          type: string
          description: Value to apply
      title: Patch Operation
    title: Patch Array
  'Status':
    type: object
    properties:
      status:
        type: string