swagger: '2.0'
info:
  version: 5.5.0
  title: ForgeRock AM OAuth2Client API
basePath: /openam
tags:
  - name: OAuth2 Client Agents
schemes:
  - http
  - https
consumes:
  - application/json
  - text/plain
  - multipart/form-data
produces:
  - application/json
paths:
  /json/realms/root/realms/{realm}/realm-config/agents/OAuth2Client:
    get:
      summary: Query by Filter
      operationId: queryFilter
      parameters:
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/_queryFilter'
        - $ref: '#/parameters/realm'
        - $ref: '#/parameters/authorization'
        - name: _pagedResultsOffset
          in: query
          required: false
          type: string
        - name: _pagedResultsCookie
          in: query
          required: false
          type: string
        - name: _pageSize
          in: query
          required: false
          type: integer
        - name: _totalPagedResultsPolicy
          in: query
          required: false
          type: string
          enum:
            - NONE
        - name: _sortKeys
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/OAuth2ClientsResultSet'
      description: Querying the agents of a specific type
      tags:
        - OAuth2 Client Agents
    post:
      summary: 'Action: getAllTypes'
      operationId: actionGetAllTypes
      parameters:
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/_action'
        - $ref: '#/parameters/realm'
        - $ref: '#/parameters/authorization'
      responses:
        '200':
          description: Success
          schema:
            type: object
      description: Call the endpoint with various actions
      tags:
        - OAuth2 Client Agents
  '/json/realms/root/realms/{realm}/realm-config/agents/OAuth2Client/{id}':
    get:
      summary: Read
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/realm'
        - $ref: '#/parameters/authorization'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/OAuth2Client'
      tags:
        - OAuth2 Client Agents
    put:
      summary: Update or Create with Client-Assigned ID
      operationId: put
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - $ref: '#/parameters/realm'
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/authorization'
        - in: body
          name: requestPayload
          required: true
          schema:
            $ref: '#/definitions/AmAgent'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/OAuth2Client'
          headers:
            Location:
              type: string
              description: Resource location in response to successful create operation.
      tags:
        - OAuth2 Client Agents
    delete:
      summary: Delete
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - $ref: '#/parameters/realm'
        - $ref: '#/parameters/_fields'
        - $ref: '#/parameters/authorization'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AmAgent'
      tags:
        - OAuth2 Client Agents
definitions:
  'OAuth2Client':
    type: object
    title: OAuth2 CRUD JSON Object
    properties:
      _id:
        type: string
      _rev:
        type: string
      signEncOAuth2ClientConfig:
        type: object
        properties:
          tokenEndpointAuthSigningAlgorithm:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          jwkSet:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          jwksCacheTimeout:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
          idTokenEncryptionMethod:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          clientJwtPublicKey:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          idTokenSignedResponseAlg:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          userinfoEncryptedResponseAlg:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          userinfoSignedResponseAlg:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          requestParameterEncryptedAlg:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          requestParameterSignedAlg:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          userinfoResponseFormat:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          idTokenEncryptionEnabled:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: boolean
          idTokenPublicEncryptionKey:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          jwksUri:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          idTokenEncryptionAlgorithm:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          requestParameterEncryptedEncryptionAlgorithm:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          userinfoEncryptedResponseEncryptionAlgorithm:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          jwkStoreCacheMissCacheTime:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
          publicKeyLocation:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
      advancedOAuth2ClientConfig:
        type: object
        properties:
          tokenEndpointAuthMethod:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          sectorIdentifierUri:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          responseTypes:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          isConsentImplied:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: boolean
          contacts:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          subjectType:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          descriptions:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          updateAccessToken:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          requestUris:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          name:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          mixUpMitigation:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: boolean
      coreOAuth2ClientConfig:
        type: object
        properties:
          userpassword:
            type: string
          agentgroup:
            type: object
          clientType:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          defaultScopes:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          clientName:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: string
          redirectionUris:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          accessTokenLifetime:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
          scopes:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          authorizationCodeLifetime:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
          refreshTokenLifetime:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
      coreOpenIDClientConfig:
        type: object
        properties:
          clientSessionUri:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: object
          jwtTokenLifetime:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
          claims:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          defaultMaxAge:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: integer
          postLogoutRedirectUri:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
          defaultMaxAgeEnabled:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: boolean
      coreUmaClientConfig:
        type: object
        properties:
          claimsRedirectionUris:
            type: object
            properties:
              inherited:
                type: boolean
              value:
                type: array
                items:
                  type: string
      _type:
        type: object
        properties:
          _id:
            type: string
          name:
            type: string
          collection:
            type: boolean
parameters:
  _queryFilter:
    name: _queryFilter
    in: query
    required: false
    type: string
  _action:
    name: _action
    in: query
    required: true
    type: string
    enum:
      - getAllTypes
      - getCreatableTypes
      - nextdescendents
      - schema
      - template
  If-None-Match-Star:
    name: If-None-Match
    in: header
    description: Add on PUT Operations when Creating new Entities
    required: false
    type: string
    enum:
      - '*'
  If-Match:
    name: If-Match
    in: header
    description: Add on PUT Operations when Updating Existing Entities
    required: false
    type: string
    enum:
      - '*'
  If-None-Match-Rev:
    name: If-None-Match
    in: header
    description: Add on GET Operations
    required: false
    type: string
  _fields:
    name: _fields
    in: query
    description: Optional parameter containing a comma separated list of field references specifying which fields of the targeted JSON resource should be returned.
    required: false
    type: string
    collectionFormat: csv
  realm:
    name: realm
    in: path
    required: true
    type: string
  authorization:
    name: Cookie
    in: header
    required: false
    type: string
