/*
 * ForgeRock IDM Miscellaneous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.misc.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ConnectorObject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:49:00.022Z")
public class ConnectorObject {
  @JsonProperty("_id")
  private String id = null;

  @JsonProperty("cn")
  private String cn = null;

  @JsonProperty("employeeType")
  private String employeeType = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("givenName")
  private String givenName = null;

  @JsonProperty("mail")
  private String mail = null;

  @JsonProperty("telephoneNumber")
  private String telephoneNumber = null;

  @JsonProperty("sn")
  private String sn = null;

  @JsonProperty("uid")
  private String uid = null;

  @JsonProperty("dn")
  private String dn = null;

  @JsonProperty("userPassword")
  private String userPassword = null;

  @JsonProperty("ldapGroups")
  private List<String> ldapGroups = null;

  @JsonProperty("disabled")
  private String disabled = null;

  @JsonProperty("aliasList")
  private List<String> aliasList = null;

  @JsonProperty("objectClass")
  private List<String> objectClass = null;

  @JsonProperty("kbaInfo")
  private List<String> kbaInfo = null;

  @JsonProperty("pwdAccountLockedTime")
  private String pwdAccountLockedTime = null;

  @JsonProperty("inetUserStatus")
  private String inetUserStatus = null;

  public ConnectorObject id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ConnectorObject cn(String cn) {
    this.cn = cn;
    return this;
  }

   /**
   * Get cn
   * @return cn
  **/
  @ApiModelProperty(value = "")
  public String getCn() {
    return cn;
  }

  public void setCn(String cn) {
    this.cn = cn;
  }

  public ConnectorObject employeeType(String employeeType) {
    this.employeeType = employeeType;
    return this;
  }

   /**
   * Get employeeType
   * @return employeeType
  **/
  @ApiModelProperty(value = "")
  public String getEmployeeType() {
    return employeeType;
  }

  public void setEmployeeType(String employeeType) {
    this.employeeType = employeeType;
  }

  public ConnectorObject description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ConnectorObject givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @ApiModelProperty(value = "")
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public ConnectorObject mail(String mail) {
    this.mail = mail;
    return this;
  }

   /**
   * Get mail
   * @return mail
  **/
  @ApiModelProperty(value = "")
  public String getMail() {
    return mail;
  }

  public void setMail(String mail) {
    this.mail = mail;
  }

  public ConnectorObject telephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
    return this;
  }

   /**
   * Get telephoneNumber
   * @return telephoneNumber
  **/
  @ApiModelProperty(value = "")
  public String getTelephoneNumber() {
    return telephoneNumber;
  }

  public void setTelephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }

  public ConnectorObject sn(String sn) {
    this.sn = sn;
    return this;
  }

   /**
   * Get sn
   * @return sn
  **/
  @ApiModelProperty(value = "")
  public String getSn() {
    return sn;
  }

  public void setSn(String sn) {
    this.sn = sn;
  }

  public ConnectorObject uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(value = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public ConnectorObject dn(String dn) {
    this.dn = dn;
    return this;
  }

   /**
   * Get dn
   * @return dn
  **/
  @ApiModelProperty(value = "")
  public String getDn() {
    return dn;
  }

  public void setDn(String dn) {
    this.dn = dn;
  }

  public ConnectorObject userPassword(String userPassword) {
    this.userPassword = userPassword;
    return this;
  }

   /**
   * Get userPassword
   * @return userPassword
  **/
  @ApiModelProperty(value = "")
  public String getUserPassword() {
    return userPassword;
  }

  public void setUserPassword(String userPassword) {
    this.userPassword = userPassword;
  }

  public ConnectorObject ldapGroups(List<String> ldapGroups) {
    this.ldapGroups = ldapGroups;
    return this;
  }

  public ConnectorObject addLdapGroupsItem(String ldapGroupsItem) {
    if (this.ldapGroups == null) {
      this.ldapGroups = new ArrayList<>();
    }
    this.ldapGroups.add(ldapGroupsItem);
    return this;
  }

   /**
   * Get ldapGroups
   * @return ldapGroups
  **/
  @ApiModelProperty(value = "")
  public List<String> getLdapGroups() {
    return ldapGroups;
  }

  public void setLdapGroups(List<String> ldapGroups) {
    this.ldapGroups = ldapGroups;
  }

  public ConnectorObject disabled(String disabled) {
    this.disabled = disabled;
    return this;
  }

   /**
   * Get disabled
   * @return disabled
  **/
  @ApiModelProperty(value = "")
  public String getDisabled() {
    return disabled;
  }

  public void setDisabled(String disabled) {
    this.disabled = disabled;
  }

  public ConnectorObject aliasList(List<String> aliasList) {
    this.aliasList = aliasList;
    return this;
  }

  public ConnectorObject addAliasListItem(String aliasListItem) {
    if (this.aliasList == null) {
      this.aliasList = new ArrayList<>();
    }
    this.aliasList.add(aliasListItem);
    return this;
  }

   /**
   * Get aliasList
   * @return aliasList
  **/
  @ApiModelProperty(value = "")
  public List<String> getAliasList() {
    return aliasList;
  }

  public void setAliasList(List<String> aliasList) {
    this.aliasList = aliasList;
  }

  public ConnectorObject objectClass(List<String> objectClass) {
    this.objectClass = objectClass;
    return this;
  }

  public ConnectorObject addObjectClassItem(String objectClassItem) {
    if (this.objectClass == null) {
      this.objectClass = new ArrayList<>();
    }
    this.objectClass.add(objectClassItem);
    return this;
  }

   /**
   * Get objectClass
   * @return objectClass
  **/
  @ApiModelProperty(value = "")
  public List<String> getObjectClass() {
    return objectClass;
  }

  public void setObjectClass(List<String> objectClass) {
    this.objectClass = objectClass;
  }

  public ConnectorObject kbaInfo(List<String> kbaInfo) {
    this.kbaInfo = kbaInfo;
    return this;
  }

  public ConnectorObject addKbaInfoItem(String kbaInfoItem) {
    if (this.kbaInfo == null) {
      this.kbaInfo = new ArrayList<>();
    }
    this.kbaInfo.add(kbaInfoItem);
    return this;
  }

   /**
   * Get kbaInfo
   * @return kbaInfo
  **/
  @ApiModelProperty(value = "")
  public List<String> getKbaInfo() {
    return kbaInfo;
  }

  public void setKbaInfo(List<String> kbaInfo) {
    this.kbaInfo = kbaInfo;
  }

  public ConnectorObject pwdAccountLockedTime(String pwdAccountLockedTime) {
    this.pwdAccountLockedTime = pwdAccountLockedTime;
    return this;
  }

   /**
   * Get pwdAccountLockedTime
   * @return pwdAccountLockedTime
  **/
  @ApiModelProperty(value = "")
  public String getPwdAccountLockedTime() {
    return pwdAccountLockedTime;
  }

  public void setPwdAccountLockedTime(String pwdAccountLockedTime) {
    this.pwdAccountLockedTime = pwdAccountLockedTime;
  }

  public ConnectorObject inetUserStatus(String inetUserStatus) {
    this.inetUserStatus = inetUserStatus;
    return this;
  }

   /**
   * Get inetUserStatus
   * @return inetUserStatus
  **/
  @ApiModelProperty(value = "")
  public String getInetUserStatus() {
    return inetUserStatus;
  }

  public void setInetUserStatus(String inetUserStatus) {
    this.inetUserStatus = inetUserStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorObject connectorObject = (ConnectorObject) o;
    return Objects.equals(this.id, connectorObject.id) &&
        Objects.equals(this.cn, connectorObject.cn) &&
        Objects.equals(this.employeeType, connectorObject.employeeType) &&
        Objects.equals(this.description, connectorObject.description) &&
        Objects.equals(this.givenName, connectorObject.givenName) &&
        Objects.equals(this.mail, connectorObject.mail) &&
        Objects.equals(this.telephoneNumber, connectorObject.telephoneNumber) &&
        Objects.equals(this.sn, connectorObject.sn) &&
        Objects.equals(this.uid, connectorObject.uid) &&
        Objects.equals(this.dn, connectorObject.dn) &&
        Objects.equals(this.userPassword, connectorObject.userPassword) &&
        Objects.equals(this.ldapGroups, connectorObject.ldapGroups) &&
        Objects.equals(this.disabled, connectorObject.disabled) &&
        Objects.equals(this.aliasList, connectorObject.aliasList) &&
        Objects.equals(this.objectClass, connectorObject.objectClass) &&
        Objects.equals(this.kbaInfo, connectorObject.kbaInfo) &&
        Objects.equals(this.pwdAccountLockedTime, connectorObject.pwdAccountLockedTime) &&
        Objects.equals(this.inetUserStatus, connectorObject.inetUserStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, cn, employeeType, description, givenName, mail, telephoneNumber, sn, uid, dn, userPassword, ldapGroups, disabled, aliasList, objectClass, kbaInfo, pwdAccountLockedTime, inetUserStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorObject {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cn: ").append(toIndentedString(cn)).append("\n");
    sb.append("    employeeType: ").append(toIndentedString(employeeType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    mail: ").append(toIndentedString(mail)).append("\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("    sn: ").append(toIndentedString(sn)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    dn: ").append(toIndentedString(dn)).append("\n");
    sb.append("    userPassword: ").append(toIndentedString(userPassword)).append("\n");
    sb.append("    ldapGroups: ").append(toIndentedString(ldapGroups)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    aliasList: ").append(toIndentedString(aliasList)).append("\n");
    sb.append("    objectClass: ").append(toIndentedString(objectClass)).append("\n");
    sb.append("    kbaInfo: ").append(toIndentedString(kbaInfo)).append("\n");
    sb.append("    pwdAccountLockedTime: ").append(toIndentedString(pwdAccountLockedTime)).append("\n");
    sb.append("    inetUserStatus: ").append(toIndentedString(inetUserStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

