/*
 * ForgeRock IDM Miscellaneous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.misc.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ReconServiceResultSet
 */
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:49:00.022Z")
public class ReconServiceResultSet {
  @JsonProperty("reconciliations")
  private List<ReconciliationServiceResource> reconciliations = new ArrayList<>();

  public ReconServiceResultSet reconciliations(List<ReconciliationServiceResource> reconciliations) {
    this.reconciliations = reconciliations;
    return this;
  }

  public ReconServiceResultSet addReconciliationsItem(ReconciliationServiceResource reconciliationsItem) {
    this.reconciliations.add(reconciliationsItem);
    return this;
  }

   /**
   * Get reconciliations
   * @return reconciliations
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ReconciliationServiceResource> getReconciliations() {
    return reconciliations;
  }

  public void setReconciliations(List<ReconciliationServiceResource> reconciliations) {
    this.reconciliations = reconciliations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReconServiceResultSet reconServiceResultSet = (ReconServiceResultSet) o;
    return Objects.equals(this.reconciliations, reconServiceResultSet.reconciliations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reconciliations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReconServiceResultSet {\n");
    
    sb.append("    reconciliations: ").append(toIndentedString(reconciliations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

