/*
 * ForgeRock IDM Miscellaneous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.misc.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Recon progress stats
 */
@ApiModel(description = "Recon progress stats")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:49:00.022Z")
public class ReconProgress {
  @JsonProperty("source")
  private Object source = null;

  @JsonProperty("target")
  private Object target = null;

  @JsonProperty("links")
  private Object links = null;

  public ReconProgress source(Object source) {
    this.source = source;
    return this;
  }

   /**
   * Stats for source objects
   * @return source
  **/
  @ApiModelProperty(required = true, value = "Stats for source objects")
  public Object getSource() {
    return source;
  }

  public void setSource(Object source) {
    this.source = source;
  }

  public ReconProgress target(Object target) {
    this.target = target;
    return this;
  }

   /**
   * Stats for target objects
   * @return target
  **/
  @ApiModelProperty(required = true, value = "Stats for target objects")
  public Object getTarget() {
    return target;
  }

  public void setTarget(Object target) {
    this.target = target;
  }

  public ReconProgress links(Object links) {
    this.links = links;
    return this;
  }

   /**
   * Stats for links
   * @return links
  **/
  @ApiModelProperty(required = true, value = "Stats for links")
  public Object getLinks() {
    return links;
  }

  public void setLinks(Object links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReconProgress reconProgress = (ReconProgress) o;
    return Objects.equals(this.source, reconProgress.source) &&
        Objects.equals(this.target, reconProgress.target) &&
        Objects.equals(this.links, reconProgress.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, target, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReconProgress {\n");
    
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

