/*
 * ForgeRock IDM Miscellaneous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.misc.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ReconStateResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T13:49:00.022Z")
public class ReconStateResponse {
  @JsonProperty("state")
  private String state = null;

  @JsonProperty("_id")
  private String id = null;

  public ReconStateResponse state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Recon state (ACTIVE, CANCELED, FAILED, SUCCESS)
   * @return state
  **/
  @ApiModelProperty(required = true, value = "Recon state (ACTIVE, CANCELED, FAILED, SUCCESS)")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ReconStateResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Recon ID
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Recon ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReconStateResponse reconStateResponse = (ReconStateResponse) o;
    return Objects.equals(this.state, reconStateResponse.state) &&
        Objects.equals(this.id, reconStateResponse.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReconStateResponse {\n");
    
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

