/*
 * Forgerock Shared Definitions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.shared.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL;

/**
 * PatchOperation
 */
@JsonInclude(NON_NULL)
public class PatchOperation {
  @JsonProperty("operation")
  private String operation = null;

  @JsonProperty("field")
  private String field = null;

  @JsonProperty("from")
  private String from = null;

  @JsonProperty("value")
  private Object value = null;

  public PatchOperation operation(String operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Operation to perform on the field
   * @return operation
  **/
  @ApiModelProperty(value = "Operation to perform on the field")
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public PatchOperation field(String field) {
    this.field = field;
    return this;
  }

   /**
   * Target JSON Pointer of field to patch
   * @return field
  **/
  @ApiModelProperty(value = "Target JSON Pointer of field to patch")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public PatchOperation from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Source JSON Pointer used with copy and move operations
   * @return from
  **/
  @ApiModelProperty(value = "Source JSON Pointer used with copy and move operations")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public PatchOperation value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Value to apply
   * @return value
  **/
  @ApiModelProperty(value = "Value to apply")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchOperation patchOperation = (PatchOperation) o;
    return Objects.equals(this.operation, patchOperation.operation) &&
        Objects.equals(this.field, patchOperation.field) &&
        Objects.equals(this.from, patchOperation.from) &&
        Objects.equals(this.value, patchOperation.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, field, from, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchOperation {\n");
    
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

