/*
 * API Explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.5.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.hmcts.reform.idam.api.fr.idm.manage.assignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AssignmentAttributesItems
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-07T14:02:15.087+01:00")
public class AssignmentAttributesItems {
  @JsonProperty("assignmentOperation")
  private String assignmentOperation = null;

  @JsonProperty("unassignmentOperation")
  private String unassignmentOperation = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("value")
  private List<String> value = null;

  public AssignmentAttributesItems assignmentOperation(String assignmentOperation) {
    this.assignmentOperation = assignmentOperation;
    return this;
  }

  /**
   * Assignment operation
   * @return assignmentOperation
   **/
  @ApiModelProperty(value = "Assignment operation")
  public String getAssignmentOperation() {
    return assignmentOperation;
  }

  public void setAssignmentOperation(String assignmentOperation) {
    this.assignmentOperation = assignmentOperation;
  }

  public AssignmentAttributesItems unassignmentOperation(String unassignmentOperation) {
    this.unassignmentOperation = unassignmentOperation;
    return this;
  }

  /**
   * Unassignment operation
   * @return unassignmentOperation
   **/
  @ApiModelProperty(value = "Unassignment operation")
  public String getUnassignmentOperation() {
    return unassignmentOperation;
  }

  public void setUnassignmentOperation(String unassignmentOperation) {
    this.unassignmentOperation = unassignmentOperation;
  }

  public AssignmentAttributesItems name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name
   * @return name
   **/
  @ApiModelProperty(value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AssignmentAttributesItems value(List<String> value) {
    this.value = value;
    return this;
  }

  public AssignmentAttributesItems addValueItem(String valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

  /**
   * Value
   * @return value
   **/
  @ApiModelProperty(value = "Value")
  public List<String> getValue() {
    return value;
  }

  public void setValue(List<String> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignmentAttributesItems assignmentAttributesItems = (AssignmentAttributesItems) o;
    return Objects.equals(this.assignmentOperation, assignmentAttributesItems.assignmentOperation) &&
            Objects.equals(this.unassignmentOperation, assignmentAttributesItems.unassignmentOperation) &&
            Objects.equals(this.name, assignmentAttributesItems.name) &&
            Objects.equals(this.value, assignmentAttributesItems.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignmentOperation, unassignmentOperation, name, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignmentAttributesItems {\n");

    sb.append("    assignmentOperation: ").append(toIndentedString(assignmentOperation)).append("\n");
    sb.append("    unassignmentOperation: ").append(toIndentedString(unassignmentOperation)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

